export const TANSTACK_REQUEST_CACHE_TAGS = {
  FETCH_SINGLE_USER: "FETCH_SINGLE_USER",
  FETCH_SINGLE_ADMIN: "FETCH_SINGLE_ADMIN",

  // New
  FETCH_AGENTS: "FETCH_AGENTS",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",

  FETCH_E_COMMERCE_BUYERS: "FETCH_E_COMMERCE_BUYERS",
  FETCH_E_COMMERCE_DISTRIBUTORS: "FETCH_E_COMMERCE_DISTRIBUTORS",
  FETCH_ALl_WORKERS: "FETCH_ALl_WORKERS:",

  FETCH_RECENT_ORDERS: "FETCH_RECENT_ORDERS",
  FETCH_SINGLE_AGENT: "FETCH_SINGLE_AGENT",
  FETCH_SINGLE_CATEGORY: "FETCH_SINGLE_CATEGORY",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_ORDERS: "FETCH_ORDERS",
  FETCH_ASSIGNED_ORDERS: "FETCH_ASSIGNED_ORDERS",
  FETCH_SINGLE_ORDER: "FETCH_SINGLE_ORDER",
  FETCH_SINGLE_USER_ORDERS: "FETCH_SINGLE_USER_ORDERS",
  FETCH_SINGLE_USER_FOLLOWERS: "FETCH_SINGLE_USER_FOLLOWERS",
  FETCH_SINGLE_USER_ACTIVE_ORDERS: "FETCH_SINGLE_USER_ACTIVE_ORDERS",
  FETCH_SINGLE_VENDOR_ACTIVE_ORDERS: "FETCH_SINGLE_VENDOR_ACTIVE_ORDERS",
  FETCH_SINGLE_VENDOR_OVERVIEW: "FETCH_SINGLE_VENDOR_OVERVIEW",
  FETCH_SINGLE_VENDOR_RATE_AND_REVIEWS: "FETCH_SINGLE_VENDOR_RATE_AND_REVIEWS",
  FETCH_SINGLE_VENDOR_CATEGORIES_AND_ACTIVITIES:
    "FETCH_SINGLE_VENDOR_CATEGORIES_AND_ACTIVITIES",
  FETCH_SINGLE_VENDOR_ESCROW_DATA: "FETCH_SINGLE_VENDOR_ESCROW_DATA",
  FETCH_SINGLE_VENDOR_FEEDS_AND_FOLLOWERS:
    "FETCH_SINGLE_VENDOR_FEEDS_AND_FOLLOWERS",
  FETCH_SINGLE_WORKER_OVERVIEW: "FETCH_SINGLE_WORKER_OVERVIEW",
  FETCH_SINGLE_WORKER_JOB_REQUESTS: "FETCH_SINGLE_WORKER_JOB_REQUESTS",
  FETCH_SINGLE_WORKER_REVIEWS: "FETCH_SINGLE_WORKER_REVIEWS",
  FETCH_ADMIN_DASHBOARD_OVERVIEW: "FETCH_ADMIN_DASHBOARD_OVERVIEW",
};
