import { appPermissions } from "./permissions";

export const adminRoles = {
  SUPER_ADMIN: "superadmin",
  MEDIA_MARKETING_ADMIN: "mediamarketingadmin",
  RISK_MANAGER: "riskmanager",
  FINANCE_ADMIN: "financeadmin",
  SUPER_ACCOUNTANT: "superaccountant",
  ACCOUNTANT: "accountant",
  ACCOUNT_MANAGER: "accountmanager",
  CUSTOMER_CARE_ADMIN: "customercareadmin",
  PRODUCT_MANAGER: "product-manager",
  EVENT_MANAGER: "event-manager",
  ORDINARY_EVENT_MANAGER: "ordinary-event-manager",
};
const rolesPermissions = {
  [adminRoles.ACCOUNTANT]: [
    appPermissions.can_read_all_transactions,
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_tickets,
    appPermissions.can_download_tickets,
    appPermissions.can_read_player_reports,
    appPermissions.can_read_agent_reports,
    appPermissions.can_download_players_reports,
    appPermissions.can_download_agents_reports,
    appPermissions.can_read_all_dealers,
    appPermissions.can_read_dealers_reports,
  ],
  [adminRoles.RISK_MANAGER]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_draw_results,
    appPermissions.can_upload_draw_result,
    appPermissions.can_read_all_events_results,
    appPermissions.can_read_one_event,
    appPermissions.can_upload_event_result,
    appPermissions.can_approve_event_result,
    appPermissions.can_approve_draw_result,
    appPermissions.can_read_all_bonuses,
    appPermissions.can_read_one_bonus,
    appPermissions.can_create_bonus,
    appPermissions.can_read_all_bundles,
    appPermissions.can_read_one_bundle,
    appPermissions.can_create_bundle,
    appPermissions.can_activate_deactivate_bundle,
    appPermissions.can_create_bonus,
    appPermissions.can_activate_deactivate_bonus,
    appPermissions.can_read_all_lotteries,
    appPermissions.can_read_one_lottery,
    appPermissions.can_create_lottery,
    appPermissions.can_update_lottery,
    appPermissions.can_read_all_games,
    appPermissions.can_create_game,
    appPermissions.can_update_game,
    appPermissions.can_activate_deactivate_game,
    appPermissions.can_read_all_banners,
    appPermissions.can_create_banner,
    appPermissions.can_update_banner,
    appPermissions.can_read_all_static_pages,
    appPermissions.can_create_static_page,
    appPermissions.can_update_static_page,
    appPermissions.can_read_all_lotto_products,
    appPermissions.can_read_all_sports_products,
    appPermissions.can_read_all_main_products,
    appPermissions.can_create_lotto_product,
    appPermissions.can_create_sport_product,
    appPermissions.can_create_product_category,
    appPermissions.can_read_all_leagues,
    appPermissions.can_read_all_teams,
    appPermissions.can_read_one_event,
    appPermissions.can_read_all_events,
    appPermissions.can_create_league,
    appPermissions.can_read_one_league,
    appPermissions.can_update_league,
    appPermissions.can_activate_deactivate_league,
    appPermissions.can_create_team,
    appPermissions.can_update_team,
    appPermissions.can_read_one_team,
    appPermissions.can_activate_deactivate_team,
    appPermissions.can_create_event,
    appPermissions.can_update_event,
    appPermissions.can_activate_deactivate_event,
    appPermissions.can_read_tickets,
    appPermissions.can_read_player_reports,
    appPermissions.can_read_agent_reports,
    appPermissions.can_read_all_dealers,
    appPermissions.can_read_lottery_images,
    appPermissions.can_read_all_static_pages,
  ],
  [adminRoles.EVENT_MANAGER]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_all_events,
    appPermissions.can_read_one_event,
    appPermissions.can_upload_event_result,
    appPermissions.can_approve_event_result,
    appPermissions.can_approve_draw_result,
    appPermissions.can_read_all_leagues,
    appPermissions.can_read_one_league,
    appPermissions.can_create_league,
    appPermissions.can_update_league,
    appPermissions.can_activate_deactivate_league,
    appPermissions.can_read_all_teams,
    appPermissions.can_read_one_team,
    appPermissions.can_create_team,
    appPermissions.can_update_team,
    appPermissions.can_activate_deactivate_team,
    appPermissions.can_read_all_events,
    appPermissions.can_read_one_event,
    appPermissions.can_create_event,
    appPermissions.can_activate_deactivate_event,
    appPermissions.can_read_tickets,
    appPermissions.can_read_one_ticket,
    appPermissions.can_read_all_static_pages,
  ],
  [adminRoles.ORDINARY_EVENT_MANAGER]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_all_events,
    appPermissions.can_read_one_event,
    appPermissions.can_upload_event_result,
    appPermissions.can_read_all_leagues,
    appPermissions.can_read_one_league,
    appPermissions.can_read_all_teams,
    appPermissions.can_read_one_team,
    appPermissions.can_read_all_events,
    appPermissions.can_read_one_event,
    appPermissions.can_create_event,
    appPermissions.can_activate_deactivate_event,
    appPermissions.can_read_tickets,
    appPermissions.can_read_one_ticket,
    appPermissions.can_read_all_static_pages,
  ],
  [adminRoles.FINANCE_ADMIN]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_withdrawal_requests,
    appPermissions.can_read_one_withdrawal_request,
    appPermissions.can_run_winning_checks,
    appPermissions.can_read_tickets,
    appPermissions.can_read_one_ticket,
    appPermissions.can_download_tickets,
    appPermissions.can_read_player_reports,
    appPermissions.can_read_agent_reports,
    appPermissions.can_download_players_reports,
    appPermissions.can_download_agents_reports,
    appPermissions.can_read_all_dealers,
    appPermissions.can_read_all_static_pages,
  ],
  [adminRoles.PRODUCT_MANAGER]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_all_lotteries,
    appPermissions.can_read_one_lottery,
    appPermissions.can_read_one_league,
    appPermissions.can_create_lottery,
    appPermissions.can_update_lottery,
    appPermissions.can_read_all_games,
    appPermissions.can_create_game,
    appPermissions.can_update_game,
    appPermissions.can_activate_deactivate_game,
    appPermissions.can_read_all_banners,
    appPermissions.can_read_one_banner,
    appPermissions.can_create_banner,
    appPermissions.can_update_banner,
    appPermissions.can_read_all_static_pages,
    appPermissions.can_read_one_static_page,
    appPermissions.can_create_static_page,
    appPermissions.can_update_static_page,
    appPermissions.can_read_all_main_products,
    appPermissions.can_read_all_lotto_products,
    appPermissions.can_read_all_sports_products,
    appPermissions.can_read_all_leagues,
    appPermissions.can_read_one_league,
    appPermissions.can_create_league,
    appPermissions.can_update_league,
    appPermissions.can_activate_deactivate_league,
    appPermissions.can_read_all_teams,
    appPermissions.can_read_one_team,
    appPermissions.can_create_team,
    appPermissions.can_update_team,
    appPermissions.can_activate_deactivate_team,
    appPermissions.can_read_all_events,
    appPermissions.can_read_one_event,
    appPermissions.can_create_event,
    appPermissions.can_activate_deactivate_event,
    appPermissions.can_read_tickets,
    appPermissions.can_read_one_ticket,
    appPermissions.can_read_player_reports,
    appPermissions.can_read_agent_reports,
    appPermissions.can_read_all_dealers,
    appPermissions.can_read_lottery_images,
  ],
  [adminRoles.ACCOUNT_MANAGER]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_tickets,
    appPermissions.can_read_one_ticket,
    appPermissions.can_read_all_dealers,
    appPermissions.can_read_all_static_pages,
    appPermissions.can_read_one_static_page,
  ],
  [adminRoles.SUPER_ACCOUNTANT]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_fund_user_account,
    appPermissions.can_retract_fund_from_user_account,
    appPermissions.can_read_all_bonuses,
    appPermissions.can_read_one_bonus,
    appPermissions.can_create_bonus,
    appPermissions.can_activate_deactivate_bonus,
    appPermissions.can_read_all_bundles,
    appPermissions.can_read_one_bundle,
    appPermissions.can_create_bundle,
    appPermissions.can_activate_deactivate_bundle,
    appPermissions.can_read_withdrawal_requests,
    appPermissions.can_read_one_withdrawal_request,
    appPermissions.can_approve_cancel_withdrawal_request,
    appPermissions.can_run_winning_checks,
    appPermissions.can_read_tickets,
    appPermissions.can_read_one_ticket,
    appPermissions.can_download_tickets,
    appPermissions.can_read_player_reports,
    appPermissions.can_read_agent_reports,
    appPermissions.can_download_players_reports,
    appPermissions.can_download_agents_reports,
    appPermissions.can_read_all_dealers,
    appPermissions.can_read_all_static_pages,
    appPermissions.can_read_one_static_page,
  ],
  [adminRoles.MEDIA_MARKETING_ADMIN]: [
    appPermissions.can_read_all_users,
    appPermissions.can_read_one_user,
    appPermissions.can_read_all_agents,
    appPermissions.can_read_one_agent,
    appPermissions.can_read_all_banners,
    appPermissions.can_read_one_banner,
    appPermissions.can_create_banner,
    appPermissions.can_update_banner,
    appPermissions.can_read_all_static_pages,
    appPermissions.can_read_one_static_page,
    appPermissions.can_create_static_page,
    appPermissions.can_update_static_page,
    appPermissions.can_read_tickets,
    appPermissions.can_read_one_ticket,
    appPermissions.can_read_lottery_images,
    appPermissions.can_read_all_static_pages,
  ],
};

export default rolesPermissions;
