export const ADMIN_ROUTE_SUB_LINKS = {
  OVERVIEW: "overview",
  USER_MANAGEMENT: "users",
  CATEGORY_MANAGEMENT: "categories",
  SINGLE_CATEGORY_PAGE: "categories/details",
  ORDER_MANGEMENT: "orders",
  ESCROW_DASHBOARD: "escrow",
  MESSAGES: "messages",
  AGENT: "agents",
  SETTINGS: "settings",
  HELP_AND_SUPPORT: "help-and-support",
  ACCOUNT: "account",
  AGENT_PROFILE: "agents/profile",
};
export const ADMIN_ROUTE_LINKS = {
  ADMIN_OVERVIEW: `/admin/${ADMIN_ROUTE_SUB_LINKS.OVERVIEW}`,
  ADMIN_USER_MANAGEMENT: `/admin/${ADMIN_ROUTE_SUB_LINKS.USER_MANAGEMENT}`,
  ADMIN_CATEGORY_MANAGEMENT: `/admin/${ADMIN_ROUTE_SUB_LINKS.CATEGORY_MANAGEMENT}`,
  ADMIN_SINGLE_CATEGORY: `/admin/${ADMIN_ROUTE_SUB_LINKS.SINGLE_CATEGORY_PAGE}`,
  ADMIN_ORDER_MANGEMENT: `/admin/${ADMIN_ROUTE_SUB_LINKS.ORDER_MANGEMENT}`,
  ADMIN_ESCROW_DASHBOARD: `/admin/${ADMIN_ROUTE_SUB_LINKS.ESCROW_DASHBOARD}`,
  ADMIN_MESSAGES: `/admin/${ADMIN_ROUTE_SUB_LINKS.MESSAGES}`,
  ADMIN_AGENT: `/admin/${ADMIN_ROUTE_SUB_LINKS.AGENT}`,
  ADMIN_SETTINGS: `/admin/${ADMIN_ROUTE_SUB_LINKS.SETTINGS}`,
  ADMIN_HELP_AND_SUPPORT: `/admin/${ADMIN_ROUTE_SUB_LINKS.HELP_AND_SUPPORT}`,
  ADMIN_ACCOUNT: `/admin/${ADMIN_ROUTE_SUB_LINKS.ACCOUNT}`,
  ADMIN_AGENT_PROFILE: `/admin/${ADMIN_ROUTE_SUB_LINKS.AGENT_PROFILE}`,
};

export const GLOBAL_ROUTE_LINKS = {
  NOT_FOUND: "/not-found",
};
